/*
 * Author: Juan Luis Su�rez D�az
 * September, 2015
 * Card Games
 */
package cardgames;

import javax.swing.JOptionPane;

/**
 *
 * @author Juan Luis
 */
public class AboutView extends javax.swing.JDialog {

    /**
     * Creates new form AboutView
     */
    public AboutView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setProgramData();
    }
    
    private void setProgramData(){
        txtProgramInfo.setText(Data.Txt.PROGRAM_INFO);
        txtLastVersion.setText(Data.Txt.LAST_VERSION_INFO);
        txtOldVersions.setText(Data.Txt.OLD_VERSIONS_INFO);
        setAuthorsData();
        //programInfoScroll.getVerticalScrollBar().setValue(0);
        //lastVersionScroll.getVerticalScrollBar().setValue(0);
        //oldVersionsScroll.getVerticalScrollBar().setValue(0);
        //authorsScroll.getVerticalScrollBar().setValue(0);        
        txtProgramInfo.setCaretPosition(0);
        txtLastVersion.setCaretPosition(0);
        txtOldVersions.setCaretPosition(0);
        txtAuthors.setCaretPosition(0);
    }
    
    private void setAuthorsData(){
        txtAuthors.setText("");
        String flags[] = {"MAIN","GRAPHICS","SOUND","GAME","THANKS"};
        int currentFlagIndex = -1;
        String[][] authors = Data.Txt.AUTHORS;
        for(int i = 0; i < authors.length; i++){
            boolean newSection = false;
            while(currentFlagIndex == -1 || (flags[currentFlagIndex] != authors[i][0] && (flags[currentFlagIndex] != "GAME" || authors[i][0] == "THANKS"))){
                newSection = true;
                currentFlagIndex++;
                if(currentFlagIndex > flags.length){
                    JOptionPane.showMessageDialog(this, "ERROR", "Sintaxis de autores incorrecta.", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            if(newSection) switch(authors[i][0]){
                case "GRAPHICS":
                    addAuthorText("\nGRÁFICOS:\n");
                    break;
                case "SOUND":
                    addAuthorText("\nSONIDO:\n");
                    break;
                case "GAME":
                    addAuthorText("\nJUEGOS:\n");
                    break;
                case "THANKS":
                    addAuthorText("\nAGRADECIMIENTOS:\n");
                    break;
            }
            String tabOrNot=authors[i][0] == "MAIN"?"":(authors[i][0]!="GAME"&&flags[currentFlagIndex]=="GAME"?"      ":"   ");
            addAuthorText(tabOrNot+authors[i][1]+":\n");
            for(int j=2; j < authors[i].length; j++){
                addAuthorText(tabOrNot+"   "+authors[i][j]+"\n");
            }
        }
    }
    
    private void addAuthorText(String text){
        txtAuthors.setText(txtAuthors.getText()+text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLab = new javax.swing.JLabel();
        programInfoScroll = new javax.swing.JScrollPane();
        txtProgramInfo = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        authorsScroll = new javax.swing.JScrollPane();
        txtAuthors = new javax.swing.JEditorPane();
        jLabel2 = new javax.swing.JLabel();
        lastVersionScroll = new javax.swing.JScrollPane();
        txtLastVersion = new javax.swing.JEditorPane();
        jLabel3 = new javax.swing.JLabel();
        oldVersionsScroll = new javax.swing.JScrollPane();
        txtOldVersions = new javax.swing.JEditorPane();
        versionLab = new javax.swing.JLabel();
        copyrightLab = new javax.swing.JLabel();
        editionLab = new javax.swing.JLabel();
        picLab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        titleLab.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        titleLab.setForeground(new java.awt.Color(51, 102, 255));
        titleLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLab.setText("<html><div style=\"text-align: center;\"> JUEGOS DE <br>   CARTAS </html>");

        programInfoScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtProgramInfo.setEditable(false);
        txtProgramInfo.setText("Información del programa");
        programInfoScroll.setViewportView(txtProgramInfo);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AUTORES");

        authorsScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtAuthors.setEditable(false);
        txtAuthors.setText("Información del programa");
        authorsScroll.setViewportView(txtAuthors);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("VERSIÓN ACTUAL");

        lastVersionScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtLastVersion.setEditable(false);
        txtLastVersion.setText("Información del programa");
        lastVersionScroll.setViewportView(txtLastVersion);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("VERSIONES ANTERIORES");

        oldVersionsScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtOldVersions.setEditable(false);
        txtOldVersions.setText("Información del programa");
        oldVersionsScroll.setViewportView(txtOldVersions);

        versionLab.setFont(new java.awt.Font("Calibri", 2, 11)); // NOI18N
        versionLab.setForeground(new java.awt.Color(0, 0, 255));
        versionLab.setText(Data.Txt.VERSION + " ");

        copyrightLab.setFont(new java.awt.Font("Calibri", 2, 11)); // NOI18N
        copyrightLab.setForeground(new java.awt.Color(0, 0, 255));
        copyrightLab.setText(Data.Txt.COPYRIGHT);

        editionLab.setFont(new java.awt.Font("Calibri", 2, 11)); // NOI18N
        editionLab.setForeground(new java.awt.Color(0, 0, 255));
        editionLab.setText(Data.Txt.EDITION);

        picLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/program_icon.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(programInfoScroll, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titleLab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(authorsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(picLab))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(editionLab, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(copyrightLab, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(versionLab, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lastVersionScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                    .addComponent(oldVersionsScroll))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(programInfoScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(authorsScroll)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastVersionScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(oldVersionsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 11, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(picLab, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(editionLab)
                                    .addComponent(versionLab))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(copyrightLab)
                                .addGap(46, 46, 46))))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AboutView dialog = new AboutView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane authorsScroll;
    private javax.swing.JLabel copyrightLab;
    private javax.swing.JLabel editionLab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane lastVersionScroll;
    private javax.swing.JScrollPane oldVersionsScroll;
    private javax.swing.JLabel picLab;
    private javax.swing.JScrollPane programInfoScroll;
    private javax.swing.JLabel titleLab;
    private javax.swing.JEditorPane txtAuthors;
    private javax.swing.JEditorPane txtLastVersion;
    private javax.swing.JEditorPane txtOldVersions;
    private javax.swing.JEditorPane txtProgramInfo;
    private javax.swing.JLabel versionLab;
    // End of variables declaration//GEN-END:variables
}
