/*
 * Author: Juan Luis Su�rez D�az
 * September, 2015
 * Card Games
 */
package cardgames;

import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonModel;
import javax.swing.JRadioButton;

/**
 *
 * @author Juan Luis
 */
public class IntroGames extends javax.swing.JDialog {

    private GameSelection game;
    
    /**
     * Creates new form IntroGames
     */
    public IntroGames(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.addWindowListener (new WindowAdapter() {
            @Override
            public void windowClosing (WindowEvent e) {
                System.exit(0);
            }
        });
    }

    public GameSelection getGame(){
        this.setVisible(true);
        return game;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gamesBtGrp = new javax.swing.ButtonGroup();
        titleLab = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btPlay = new javax.swing.JButton();
        btExit = new javax.swing.JButton();
        rbPoker = new javax.swing.JRadioButton();
        rbUno = new javax.swing.JRadioButton();
        rbSotaCabrona = new javax.swing.JRadioButton();
        rbHearts = new javax.swing.JRadioButton();
        rbTexasHoldem = new javax.swing.JRadioButton();
        rbSolitaire = new javax.swing.JRadioButton();
        rbBroom = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Card Games");
        setAlwaysOnTop(true);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Media/program_icon.png")));
        setResizable(false);

        titleLab.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        titleLab.setForeground(new java.awt.Color(51, 102, 255));
        titleLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLab.setText("<html><div style=\"text-align: center;\"> JUEGOS DE <br>   CARTAS </html>");

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel1.setText("Selecciona el juego al que deseas jugar:");

        btPlay.setBackground(new java.awt.Color(0, 204, 102));
        btPlay.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btPlay.setForeground(new java.awt.Color(255, 255, 255));
        btPlay.setText("JUGAR");
        btPlay.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPlayActionPerformed(evt);
            }
        });

        btExit.setBackground(new java.awt.Color(255, 0, 0));
        btExit.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btExit.setForeground(new java.awt.Color(255, 255, 255));
        btExit.setText("SALIR");
        btExit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });

        gamesBtGrp.add(rbPoker);
        rbPoker.setSelected(true);
        rbPoker.setText("Póquer (5 Draw)");
        rbPoker.setActionCommand("POKER");

        gamesBtGrp.add(rbUno);
        rbUno.setText("Uno");
        rbUno.setActionCommand("UNO");

        gamesBtGrp.add(rbSotaCabrona);
        rbSotaCabrona.setText("Sota Cabrona");
        rbSotaCabrona.setActionCommand("SOTA_CABRONA");

        gamesBtGrp.add(rbHearts);
        rbHearts.setText("Corazones");
        rbHearts.setActionCommand("HEARTS");

        gamesBtGrp.add(rbTexasHoldem);
        rbTexasHoldem.setText("Póquer (Texas Holdem)");
        rbTexasHoldem.setActionCommand("TEXAS_HOLDEM");

        gamesBtGrp.add(rbSolitaire);
        rbSolitaire.setText("Solitario");
        rbSolitaire.setActionCommand("SOLITAIRE");

        gamesBtGrp.add(rbBroom);
        rbBroom.setText("Escoba");
        rbBroom.setActionCommand("BROOM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbSolitaire, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(titleLab)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(rbUno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbPoker, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(btPlay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbSotaCabrona, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbHearts, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbTexasHoldem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbBroom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 108, Short.MAX_VALUE)
                        .addComponent(btExit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbPoker)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbUno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbSotaCabrona)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbHearts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbTexasHoldem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbBroom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbSolitaire)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btExitActionPerformed

    private void btPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPlayActionPerformed
    /*    switch((gamesBtGrp.getSelection().getActionCommand())){
            case "Póquer":
                game = GameSelection.POKER;
                break;
            default:
                game = GameSelection.ERROR;
                break;
        }*/
        try{
            game = GameSelection.valueOf(gamesBtGrp.getSelection().getActionCommand());
        }
        catch(IllegalArgumentException ex){
            game = GameSelection.ERROR;
        }
        this.dispose();
    }//GEN-LAST:event_btPlayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExit;
    private javax.swing.JButton btPlay;
    private javax.swing.ButtonGroup gamesBtGrp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rbBroom;
    private javax.swing.JRadioButton rbHearts;
    private javax.swing.JRadioButton rbPoker;
    private javax.swing.JRadioButton rbSolitaire;
    private javax.swing.JRadioButton rbSotaCabrona;
    private javax.swing.JRadioButton rbTexasHoldem;
    private javax.swing.JRadioButton rbUno;
    private javax.swing.JLabel titleLab;
    // End of variables declaration//GEN-END:variables
}
