/*
 * Author: Juan Luis Su�rez D�az
 * September, 2015
 * Card Games
 */
package cardgames;

import java.awt.Toolkit;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Juan Luis
 */
public class ProgramStart extends javax.swing.JDialog {

    /**
     * Creates new form ProgramStart
     */
    public ProgramStart(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        picLab = new javax.swing.JLabel();
        timeBar = new javax.swing.JProgressBar();
        titleLab = new javax.swing.JLabel();
        authorLab = new javax.swing.JLabel();
        versionLab = new javax.swing.JLabel();
        copyrightLab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Card Games");
        setAlwaysOnTop(true);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Media/program_icon.png")));
        setResizable(false);

        picLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/program_icon.png"))); // NOI18N

        titleLab.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        titleLab.setForeground(new java.awt.Color(51, 102, 255));
        titleLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLab.setText("<html><div style=\"text-align: center;\"> JUEGOS DE <br>   CARTAS </html>");

        authorLab.setFont(new java.awt.Font("Calibri", 2, 11)); // NOI18N
        authorLab.setForeground(new java.awt.Color(0, 0, 255));
        authorLab.setText("Juan Luis Suárez Díaz");

        versionLab.setFont(new java.awt.Font("Calibri", 2, 11)); // NOI18N
        versionLab.setForeground(new java.awt.Color(0, 0, 255));
        versionLab.setText("v1.0 ");

        copyrightLab.setFont(new java.awt.Font("Calibri", 2, 11)); // NOI18N
        copyrightLab.setForeground(new java.awt.Color(0, 0, 255));
        copyrightLab.setText("© 2015");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(titleLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(picLab))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(timeBar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(authorLab, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(copyrightLab, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(versionLab, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(titleLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(picLab, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authorLab)
                    .addComponent(versionLab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(copyrightLab)
                .addGap(18, 18, 18)
                .addComponent(timeBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

 
    
    public void showView(int ms){
        this.setVisible(true);
        if(ms > 0){
            timeBar.setMaximum(ms);
            timeBar.setMinimum(0);
            int i = 0;
            while(i <= ms){
                i++;
                try {
                    sleep(1);
                } catch (InterruptedException ex) {}
                timeBar.setValue(i);
            }
        }
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorLab;
    private javax.swing.JLabel copyrightLab;
    private javax.swing.JLabel picLab;
    private javax.swing.JProgressBar timeBar;
    private javax.swing.JLabel titleLab;
    private javax.swing.JLabel versionLab;
    // End of variables declaration//GEN-END:variables
}
