/*
 * Author: Juan Luis Su�rez D�az
 * September, 2015
 * Card Games
 */
package Games.Poker.GUI;

import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Juan Luis
 */
public class ChipsView extends javax.swing.JPanel {

    /**
     * Creates new form ChipsView
     */
    public ChipsView() {
        initComponents();
    }

    public void setChips(int chips){
        //this.chipsTxt.setText(Integer.toString(chips));
        int currentChips = Integer.parseInt(chipsTxt.getText());
        int repaintFrac = Math.abs(currentChips - chips)/300 + 1;
        if(currentChips < chips){
            for(int i = currentChips; i <= chips; i++){
                this.chipsTxt.setText(Integer.toString(i));                
                if(i % repaintFrac == 0) chipsTxt.paint(this.chipsTxt.getGraphics());
            }
        }
        else{
            for(int i = currentChips; i >= chips; i--){
                this.chipsTxt.setText(Integer.toString(i));
                if(i % repaintFrac == 0) chipsTxt.paint(this.chipsTxt.getGraphics());
            }
        }
        this.chipsPic.setVisible(chips!=0);
        this.repaint();
        this.revalidate();
    }
    
    public int getChips(){
        return Integer.parseInt(chipsTxt.getText());
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chipsPic = new javax.swing.JLabel();
        chipsTxt = new javax.swing.JTextField();

        chipsPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/chips_view_icon_xs.png"))); // NOI18N

        chipsTxt.setEditable(false);
        chipsTxt.setBackground(new java.awt.Color(255, 255, 255));
        chipsTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        chipsTxt.setText("0");
        chipsTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chipsTxtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chipsPic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(chipsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(chipsPic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chipsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chipsTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chipsTxtMouseClicked
        //this.setChips(this.getChips()+25);
    }//GEN-LAST:event_chipsTxtMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chipsPic;
    private javax.swing.JTextField chipsTxt;
    // End of variables declaration//GEN-END:variables
}
