/*
 * Author: Juan Luis Su�rez D�az
 * September, 2015
 * Card Games
 */
package Games.Poker.GUI;

import GUI.FrenchCardBack;
import Games.Poker.Model.PokerPlayer;
import Model.Card;
import Model.FrenchCard;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Juan Luis
 */
public class PokerPlayerView extends javax.swing.JPanel {

    private PokerPlayer playerModel;
    
    
    /**
     * Creates new form PokerPlayerView
     */
    public PokerPlayerView() {
        initComponents();
        this.dealerLab.setVisible(false);
        this.smallBlindLab.setVisible(false);
        this.bigBlindLab.setVisible(false);
        this.nameLab.setText("");
    }

    public void setPlayer(PokerPlayer p){
        this.playerModel = p;
        this.nameLab.setText(p.getName());
        this.dealerLab.setVisible(p.isDealer());
        this.bigBlindLab.setVisible(p.isBigBlind());
        this.smallBlindLab.setVisible(p.isSmallBlind());
        
        this.chipsView.setChips(p.getChips());
        this.betView.setChips(p.getBet());
        
        this.pokerHand.removeAll();
        this.pokerHand.addSelectionAtMouseListening();
        this.pokerHand.add((ArrayList<Card>)(ArrayList<? extends Card>)p.getPlayerHand(), FrenchCardBack.BLUE, false);
        
        setButtonsState();
        
        if(p.hasFolded()){
            this.setBackground(new Color(0xDF013A));
            chipsView.setBackground(new Color(0xDF013A));
            betView.setBackground(new Color(0xDF013A));
            pokerHand.setBackground(new Color(0xDF013A));
        }
        else if(p.hasLost()){
            this.setBackground(Color.DARK_GRAY);
            chipsView.setBackground(Color.DARK_GRAY);
            betView.setBackground(Color.DARK_GRAY);
            pokerHand.setBackground(Color.DARK_GRAY);
        }
        else{
            this.setBackground(null);
            chipsView.setBackground(null);
            betView.setBackground(null);
            pokerHand.setBackground(null);
        }
            
    }
    
    private void setButtonsState(){
        if(playerModel.hasLost()){
            disableIfLosing();
        }
        else{
            if(playerModel.getBet() == playerModel.getEnvironment().getCurrentCallBet()){
                this.btCall.setText("PASAR");
                this.btRaise.setText("APOSTAR");
            }
            else{
                this.btCall.setText("VER");
                this.btRaise.setText("SUBIR");               
            }
            
            this.btCall.setEnabled(playerModel.canICall());
            this.btRaise.setEnabled(playerModel.canIRaise());
            this.btFold.setEnabled(playerModel.canIFold());

            this.btDiscard.setVisible(playerModel.canIDiscard());
            
            this.btBetRaise.setEnabled(playerModel.canIRaise());
            if(playerModel.canIRaise()){
                this.btBetRaise.setModel(new SpinnerNumberModel(
                     Integer.min(playerModel.getEnvironment().getBigBlindBet(),playerModel.getChips()+playerModel.getBet()-playerModel.getEnvironment().getCurrentCallBet()), 1,
                     Integer.max(playerModel.getChips() - playerModel.getEnvironment().getCurrentCallBet() + playerModel.getBet(),0),
                     playerModel.getEnvironment().getSmallBlindBet()));
            }
        }
        
        
    }
    
    private void disableIfLosing(){
        for(Component c : this.getComponents()){
            c.setEnabled(false);
        }
    }
    
    @Override
    public void addMouseListener(MouseListener ml){
        super.addMouseListener(ml);
        for(Component c : this.getComponents()){
            c.addMouseListener(ml);
        }
    }
    
    public void forcePainting(){
        this.pokerHand.paint(this.pokerHand.getGraphics());
        //this.paint(this.getGraphics());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pokerHand = new GUI.Hand();
        bigBlindLab = new javax.swing.JLabel();
        dealerLab = new javax.swing.JLabel();
        smallBlindLab = new javax.swing.JLabel();
        btCall = new javax.swing.JButton();
        btRaise = new javax.swing.JButton();
        btFold = new javax.swing.JButton();
        btBetRaise = new javax.swing.JSpinner();
        chipsView = new Games.Poker.GUI.ChipsView();
        betView = new Games.Poker.GUI.ChipsView();
        btDiscard = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameLab = new javax.swing.JLabel();

        bigBlindLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/big_blind_icon_xs.png"))); // NOI18N

        dealerLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/dealer_icon_xs.png"))); // NOI18N

        smallBlindLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/small_blind_icon_xs.png"))); // NOI18N

        btCall.setBackground(new java.awt.Color(0, 204, 51));
        btCall.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btCall.setForeground(new java.awt.Color(255, 255, 255));
        btCall.setText("VER");
        btCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCallActionPerformed(evt);
            }
        });

        btRaise.setBackground(new java.awt.Color(0, 204, 204));
        btRaise.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btRaise.setForeground(new java.awt.Color(255, 255, 255));
        btRaise.setText("SUBIR");
        btRaise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRaiseActionPerformed(evt);
            }
        });

        btFold.setBackground(new java.awt.Color(255, 0, 0));
        btFold.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btFold.setForeground(new java.awt.Color(255, 255, 255));
        btFold.setText("NO IR");
        btFold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFoldActionPerformed(evt);
            }
        });

        btBetRaise.setModel(new javax.swing.SpinnerNumberModel(10, 1, 1000000, 5));

        btDiscard.setBackground(new java.awt.Color(255, 153, 0));
        btDiscard.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btDiscard.setForeground(new java.awt.Color(255, 255, 255));
        btDiscard.setText("DESCARTAR");
        btDiscard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDiscardActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FICHAS");

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("APUESTA");

        nameLab.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        nameLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLab.setText("NOMBRE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dealerLab, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(smallBlindLab, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bigBlindLab, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nameLab, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chipsView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(betView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pokerHand, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btCall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btRaise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btBetRaise, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btFold, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDiscard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bigBlindLab, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dealerLab, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(smallBlindLab, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(nameLab, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCall, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btRaise, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBetRaise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(betView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chipsView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btFold, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btDiscard, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pokerHand, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btCallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCallActionPerformed
        playerModel.call();
    }//GEN-LAST:event_btCallActionPerformed

    private void btRaiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRaiseActionPerformed
        playerModel.raise((int) this.btBetRaise.getValue());
    }//GEN-LAST:event_btRaiseActionPerformed

    private void btFoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFoldActionPerformed
        playerModel.fold();
    }//GEN-LAST:event_btFoldActionPerformed

    private void btDiscardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDiscardActionPerformed
        playerModel.discard((ArrayList<FrenchCard>)(ArrayList<? extends Card>) this.pokerHand.getSelectedCards());
    }//GEN-LAST:event_btDiscardActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Games.Poker.GUI.ChipsView betView;
    private javax.swing.JLabel bigBlindLab;
    private javax.swing.JSpinner btBetRaise;
    private javax.swing.JButton btCall;
    private javax.swing.JButton btDiscard;
    private javax.swing.JButton btFold;
    private javax.swing.JButton btRaise;
    private Games.Poker.GUI.ChipsView chipsView;
    private javax.swing.JLabel dealerLab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nameLab;
    private GUI.Hand pokerHand;
    private javax.swing.JLabel smallBlindLab;
    // End of variables declaration//GEN-END:variables
}
