/*
 * Author: Juan Luis Su�rez D�az
 * September, 2015
 * Card Games
 */
package Games.Poker.GUI;

import GUI.CardView;
import GUI.FrenchCardBack;
import Games.Poker.Model.PokerPlayer;
import Model.Card;
import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author Juan Luis
 */
public class RivalPlayerView extends javax.swing.JPanel {

    private PokerPlayer playerModel;
    
    private boolean covered;
    
    /**
     * Creates new form RivalPlayerView
     */
    public RivalPlayerView() {
        initComponents();
        this.covered = true;
    }

    public void setPlayer(PokerPlayer p){
        this.playerModel = p;
        this.nameLab.setText(p.getName());
        this.dealerLab.setVisible(p.isDealer());
        this.bigBlindLab.setVisible(p.isBigBlind());
        this.smallBlindLab.setVisible(p.isSmallBlind());
        
        this.chipsView.setChips(p.getChips());
        this.betView.setChips(p.getBet());
        
        if(p.getPlayerHand().size() != 5) covered = true;
        this.pokerHand.removeAll();
        this.pokerHand.add((ArrayList<Card>)(ArrayList<? extends Card>)p.getPlayerHand(), FrenchCardBack.BLUE, covered);
   
        if(p.hasFolded()){
            this.setBackground(new Color(0xDF013A));
            chipsView.setBackground(new Color(0xDF013A));
            betView.setBackground(new Color(0xDF013A));
            pokerHand.setBackground(new Color(0xDF013A));
        }
        else if(p.hasLost()){
            this.setBackground(Color.DARK_GRAY);
            chipsView.setBackground(Color.DARK_GRAY);
            betView.setBackground(Color.DARK_GRAY);
            pokerHand.setBackground(Color.DARK_GRAY);
        }
        else{
            this.setBackground(null);
            chipsView.setBackground(null);
            betView.setBackground(null);
            pokerHand.setBackground(null);
        }
        
        
    }
    
    public PokerPlayer getPlayer(){
        return playerModel;
    }
    
    public void discoverHand(){
        covered = false;
        for(CardView cv : this.pokerHand.getCardViews()){
            cv.cover(false);
        }
    }
    
    public void forcePainting(){
        this.pokerHand.paint(this.pokerHand.getGraphics());
        //this.paint(this.getGraphics());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pokerHand = new GUI.Hand();
        dealerLab = new javax.swing.JLabel();
        smallBlindLab = new javax.swing.JLabel();
        bigBlindLab = new javax.swing.JLabel();
        chipsView = new Games.Poker.GUI.ChipsView();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        betView = new Games.Poker.GUI.ChipsView();
        nameLab = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        dealerLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/dealer_icon_xs.png"))); // NOI18N

        smallBlindLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/small_blind_icon_xs.png"))); // NOI18N

        bigBlindLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/big_blind_icon_xs.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FICHAS");

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("APUESTA");

        nameLab.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        nameLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLab.setText("NOMBRE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(pokerHand, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nameLab, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dealerLab, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(smallBlindLab, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bigBlindLab, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chipsView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(betView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pokerHand, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameLab, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(smallBlindLab, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dealerLab, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bigBlindLab, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chipsView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(betView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Games.Poker.GUI.ChipsView betView;
    private javax.swing.JLabel bigBlindLab;
    private Games.Poker.GUI.ChipsView chipsView;
    private javax.swing.JLabel dealerLab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nameLab;
    private GUI.Hand pokerHand;
    private javax.swing.JLabel smallBlindLab;
    // End of variables declaration//GEN-END:variables
}
