/*
 * Author: Juan Luis Su�rez D�az
 * September, 2015
 * Card Games
 */
package GUI;

import java.awt.Dimension;
import java.awt.Toolkit;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;

/**
 *
 * @author Juan Luis
 */
public class NarratorView extends javax.swing.JDialog {

    
    /**
     * Creates new form narratorView
     */
    public NarratorView(java.awt.Frame parent) {
        super(parent, false);
        initComponents();
        
    }
    
    private Dimension setDialog(String title, String message, String icon_address){
        Dimension d = new Dimension(450, 50);
        if(title == null) titleLab.setVisible(false);
        else{
            titleLab.setText(title);
            d.setSize(d.getWidth(),d.getHeight() + titleLab.getHeight());
        }
        if(message == null) messageLab.setVisible(false);
        else{
            messageLab.setText(message);
            d.setSize(d.getWidth(),d.getHeight() + messageLab.getHeight());
        }
        if(icon_address == null) pictureLab.setVisible(false);
        else{
            try{
                pictureLab.setIcon(new javax.swing.ImageIcon(getClass().getResource(icon_address)));
                pictureLab.setSize(new Dimension(pictureLab.getIcon().getIconWidth(),pictureLab.getIcon().getIconHeight()));
                d.setSize(Integer.max((int)d.getWidth(), pictureLab.getWidth()),d.getHeight() + pictureLab.getHeight());
            }
            catch(Exception ex){
                pictureLab.setVisible(false);
            }
        }
        return d;
    }
    
    public void showDialog(int miliseconds, String title, String message, String icon_address){
        Dimension d = setDialog(title,message,icon_address);
        narratorButton.setVisible(false);
        this.setSize(d);
        
        this.setVisible(true);
        this.paintAll(this.getGraphics());
        
        this.setModal(false);
        
        try {
            sleep(miliseconds);
        } catch (InterruptedException ex) {}
        dispose();        
    }
    
    public void showDialog(String buttonText, String title, String message, String icon_address){
        Dimension d = setDialog(title,message,icon_address);
        narratorButton.setText(buttonText);
        d.setSize(d.getWidth(), d.getHeight() + narratorButton.getHeight());
        
        this.setModal(true);
        this.setVisible(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLab = new javax.swing.JLabel();
        messageLab = new javax.swing.JLabel();
        pictureLab = new javax.swing.JLabel();
        narratorButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Media/program_icon.png")));

        titleLab.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        titleLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLab.setText("Título del mensaje");

        messageLab.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        messageLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageLab.setText("Este es un mensaje informando sobre algo en un juego");

        pictureLab.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        pictureLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pictureLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/program_icon.png"))); // NOI18N
        pictureLab.setToolTipText("");

        narratorButton.setText("BOTÓN");
        narratorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                narratorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(messageLab, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                    .addComponent(pictureLab, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(narratorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pictureLab, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(titleLab, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(messageLab, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(narratorButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void narratorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_narratorButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_narratorButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NarratorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NarratorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NarratorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NarratorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NarratorView dialog = new NarratorView(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                //dialog.setVisible(true);
                dialog.showDialog(4000, "CPU 5", "¡¡REPOKER DE A!!", "/Media/few_fireworks.png");
                System.exit(0);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel messageLab;
    private javax.swing.JButton narratorButton;
    private javax.swing.JLabel pictureLab;
    private javax.swing.JLabel titleLab;
    // End of variables declaration//GEN-END:variables
}
