/*
 * Author: Juan Luis Su�rez D�az
 * September, 2015
 * Card Games
 */
package Games.SotaCabrona.GUI;

import GUI.FrenchCardBack;
import Games.SotaCabrona.Model.Player;
import Model.Card;
import Model.FrenchCard;
import Model.FrenchSuit;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;


/**
 *
 * @author Juan Luis
 */
public class PlayerView extends javax.swing.JPanel {

    Player playerModel;
    
    /**
     * Creates new form PlayerView
     */
    public PlayerView() {
        initComponents();
      
        
        timeBar.setStringPainted(true);
        timeBar.setString("");
        timeBar.setSize(timeBar.getPreferredSize());
        timeBar.setForeground(Color.RED);
        cardSizeBar.setMaximum(52);
        
    }

    public void setPlayer(Player p){
        this.playerModel = p;
        cardView.setCard(new FrenchCard("A", FrenchSuit.SPADES), 
                (p.getMyCards().size() > 0)?FrenchCardBack.BLUE:FrenchCardBack.RED, true);
        nameLab.setText(p.getName());
        cardSizeText.setText(Integer.toString(p.getMyCards().size()));
        cardSizeBar.setValue(p.getMyCards().size());
        timeBar.setMaximum(Player.getPlayerTime());
        timeBar.setValue(p.getTimerCount());
        this.setBackground((p.isMyTurn())?new Color(0xFACC2E):new Color(0xF0F0F0));
        
        if(p.isDropFlag())
            dropLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/yellow_light_xs.png")));
        else if(p.isErrorDropFlag())
            dropLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/red_light_xs.png")));
        else
            dropLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/transparent_light_xs.png")));
        
        if(p.isSameValueFlag())
            touchLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/blue_light_xs.png")));
        else if(p.isSandwichFlag())
            touchLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/green_light_xs.png")));
        else if(p.isErrorTouchFlag())
            touchLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/red_light_xs.png")));
        else
            touchLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/transparent_light_xs.png")));
        
        
        this.repaint();
        this.revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLab = new javax.swing.JLabel();
        cardView = new GUI.CardView();
        timeBar = new javax.swing.JProgressBar();
        cardSizeBar = new javax.swing.JProgressBar();
        cardSizeText = new javax.swing.JTextField();
        dropLab = new javax.swing.JLabel();
        touchLab = new javax.swing.JLabel();

        nameLab.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        nameLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLab.setText("Nombre");

        cardSizeBar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cardSizeBarStateChanged(evt);
            }
        });

        cardSizeText.setEditable(false);
        cardSizeText.setBackground(new java.awt.Color(255, 255, 255));
        cardSizeText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cardSizeText.setText("0");

        dropLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/transparent_light_xs.png"))); // NOI18N

        touchLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/transparent_light_xs.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cardView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cardSizeText, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cardSizeBar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeBar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dropLab, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(touchLab, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLab, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardView, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dropLab, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(touchLab, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cardSizeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cardSizeBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cardSizeBarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cardSizeBarStateChanged
        double frac = ((double)cardSizeBar.getValue())/((double)cardSizeBar.getMaximum());
        cardSizeBar.setStringPainted(true);
        //cardSizeBar.setString((playerModel==null)?"":Integer.toString(playerModel.getMyCards().size()));
        cardSizeBar.setString("");
        cardSizeBar.setSize(cardSizeBar.getPreferredSize());
        if(frac < 0.25){
            cardSizeBar.setForeground(new Color(0xF5A9A9));
        }
        else if(frac < 0.5){
            cardSizeBar.setForeground(new Color(0xF2F5A9));
        }
        else if(frac < 0.75){
            cardSizeBar.setForeground(new Color(0xA9F5A9));
        }
        else{
            cardSizeBar.setForeground(new Color(0xA9F5F2));
        }
    }//GEN-LAST:event_cardSizeBarStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar cardSizeBar;
    private javax.swing.JTextField cardSizeText;
    private GUI.CardView cardView;
    private javax.swing.JLabel dropLab;
    private javax.swing.JLabel nameLab;
    private javax.swing.JProgressBar timeBar;
    private javax.swing.JLabel touchLab;
    // End of variables declaration//GEN-END:variables
}
