/*
 * Author: Juan Luis Su�rez D�az
 * September, 2015
 * Card Games
 */
package Games.Broom.GUI;

import GUI.CardView;
import GUI.SpanishCardBack;
import Games.Broom.Model.Broom;
import Games.Broom.Model.Player;
import Games.Poker.Model.CPUPlayer;
import Model.SpanishCard;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author Javier
 */
public class BroomView extends javax.swing.JFrame {
    private Broom escobaModel;
    private static int RONDAS = 0;
    private Player currentPlayer;
    private void setRondas(){
        RONDAS++;
    }
    public void setBroom(Broom escobaModel){
        this.escobaModel = escobaModel;
        player1.setPlayer(escobaModel.getMyPlayer());
        CPU1.setPlayer(escobaModel.getPlayers().get(1));
        CPU2.setPlayer(escobaModel.getPlayers().get(2));       
        
        
        currentPlayer = escobaModel.getCurrentPlayer();        
        fillCardPanel(table,escobaModel.getTableCards());

        play.setEnabled(true);
        repaint();
        revalidate();
    }   
    
    private void fillCardPanel(JPanel aPanel,ArrayList <SpanishCard> aList){
        aPanel.removeAll();
        
        for(SpanishCard t: aList){
            CardView aCardView = new CardView();
            aCardView.setCard(t,SpanishCardBack.RED);
            aCardView.setVisible(true);
            aPanel.add(aCardView);
        }
        
        aPanel.repaint();
        aPanel.revalidate();
    }

    public void showView() {
        this.setVisible(true);
    }
    /**
     * Creates new form BroomView
     */
    public BroomView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        table = new javax.swing.JPanel();
        player1 = new Games.Broom.GUI.PlayerView();
        CPU1 = new Games.Broom.GUI.CPUPlayerView();
        CPU2 = new Games.Broom.GUI.CPUPlayerView();
        play = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setBorder(javax.swing.BorderFactory.createTitledBorder("Mesa"));
        table.setLayout(new java.awt.GridBagLayout());

        play.setText("Jugar");
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(CPU1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(CPU2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(player1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(306, 306, 306)
                        .addComponent(play, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 310, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CPU2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CPU1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(player1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(play, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private ArrayList<SpanishCard> getSelectedTableCards(JPanel aPanel){
        CardView tv;
        ArrayList<SpanishCard> output = new ArrayList<>();
        
        for (Component c: aPanel.getComponents()){
            tv = (CardView)c;
            
            if (tv.isSelected())
                output.add((SpanishCard)tv.getCard());
        }
        
        return output;
    }
    
    
    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        if (escobaModel.getCurrentPlayer() != escobaModel.getMyPlayer()){
            escobaModel.goodMove(null,null);
        }
        else{
        
            ArrayList<SpanishCard> selected = getSelectedTableCards(table);        
            ArrayList<SpanishCard> s = player1.getSelectedCard(player1.getCards());

            boolean goodmove = escobaModel.goodMove(s.get(0),selected);

            player1.getPlayer().discardCard(s.get(0));

            if (!goodmove){
                escobaModel.getTableCards().add(s.get(0));
            }
            else{
                if (selected.size() == escobaModel.getTableCards().size()){
                    player1.getPlayer().setScore(1);

                    for (SpanishCard c:selected){
                        player1.getPlayer().addCardHeap(c);
                        escobaModel.discardTableCard(c);
                    }

                    player1.getPlayer().addCardHeap(s.get(0));
                }
                else{
                    for (SpanishCard c:selected){
                        player1.getPlayer().addCardHeap(c);
                        escobaModel.discardTableCard(c);
                    }

                    player1.getPlayer().addCardHeap(s.get(0));
               }
            }

            //escobaModel.nextTurn(escobaModel.getCards());

            setBroom(escobaModel);
            play.setEnabled(false);
        }
        
        repaint();
        revalidate();
    }//GEN-LAST:event_playActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BroomView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BroomView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BroomView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BroomView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BroomView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Games.Broom.GUI.CPUPlayerView CPU1;
    private Games.Broom.GUI.CPUPlayerView CPU2;
    private javax.swing.JButton play;
    private Games.Broom.GUI.PlayerView player1;
    private javax.swing.JPanel table;
    // End of variables declaration//GEN-END:variables
}
