/*
 * Author: Juan Luis Su�rez D�az
 * September, 2015
 * Card Games
 */
package Games.Broom.GUI;

import GUI.CardView;
import GUI.SpanishCardBack;
import Games.Broom.Model.Broom;
import Games.Broom.Model.Player;
import Model.Card;
import Model.SpanishCard;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author Javier
 */
public class CPUPlayerView extends javax.swing.JPanel {
    private Player playerModel;
    private Broom escobaModel;
       
    public Player getPlayer(){
        return playerModel;
    }

    public JPanel getCards(){
        return cards;
    }  
    
    public void setBroom(Broom escobaModel){
        this.escobaModel = escobaModel;
        repaint();
        revalidate();
    }
        
        
    public void setPlayer(Player p){
        playerModel = p;
        name.setText(playerModel.getName());
        score.setText(Integer.toString(playerModel.getTotalPoints()));
        
        this.cards.removeAll();
        //this.cards.addSelectionAtMouseListening();
        this.cards.add((ArrayList<Card>)(ArrayList<? extends Card>)playerModel.getCards(), SpanishCardBack.RED, false);
        repaint();
        revalidate();
    }
    
    /**
     * Creates new form CPUPlayer
     */
    public CPUPlayerView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        cards = new GUI.Hand();

        name.setText("Nombre");

        score.setText("Score");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cards, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(score, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(score)
                .addGap(18, 18, 18)
                .addComponent(cards, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.Hand cards;
    private javax.swing.JLabel name;
    private javax.swing.JLabel score;
    // End of variables declaration//GEN-END:variables
}
