/*
 * Author: Juan Luis Su�rez D�az
 * September, 2015
 * Card Games
 */
package Games.Broom.GUI;

import GUI.CardView;
import GUI.SpanishCardBack;
import Games.Broom.Model.Broom;
import Games.Broom.Model.Player;
import Model.SpanishCard;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author Javier
 */
public class CPUPlayerView extends javax.swing.JPanel {
    private Player playerModel;
    private Broom escobaModel;
       
    public Player getPlayer(){
        return playerModel;
    }

    public JPanel getCards(){
        return cards;
    }  
    
    public void setBroom(Broom escobaModel){
        this.escobaModel = escobaModel;
        repaint();
        revalidate();
    }
        
        
    public void setPlayer(Player p){
        playerModel = p;
        name.setText(playerModel.getName());
        score.setText(Integer.toString(playerModel.getTotalPoints()));
        fillCardPanel(cards,playerModel.getCards());
        repaint();
        revalidate();
    }
    
    public void fillCardPanel (JPanel aPanel,ArrayList <SpanishCard> aList){
        aPanel.removeAll();
        
        for(SpanishCard t: aList){
            CardView aCardView = new CardView();
            aCardView.setCard(t,SpanishCardBack.RED,true);
            aCardView.setVisible(true);
            aPanel.add(aCardView);
        }
        
        aPanel.repaint();
        aPanel.revalidate();
    }
    
    /**
     * Creates new form CPUPlayer
     */
    public CPUPlayerView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        cards = new javax.swing.JPanel();

        name.setText("Nombre");

        score.setText("Score");

        cards.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cards.setLayout(new javax.swing.BoxLayout(cards, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cards, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(score, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(score)
                .addGap(18, 18, 18)
                .addComponent(cards, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cards;
    private javax.swing.JLabel name;
    private javax.swing.JLabel score;
    // End of variables declaration//GEN-END:variables
}
