/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Games.Broom.GUI;

import Games.Broom.Model.*;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JPanel;
/**
 *
 * @author Javier
 */
public class PlayerView extends javax.swing.JPanel {
    private Player playerModel;
    private Broom escobaModel;
    private Card taken_card;

    public Player getPlayer() {
        return playerModel;
    }

    public JPanel getCards() {
        return cards;
    }    

    public Card getTakenCard() {
        return taken_card;
    }
    
    public void setBroom(Broom escobaModel){
        this.escobaModel = escobaModel;
        repaint();
        revalidate();
    }
    public void setPlayer(Player p){
        playerModel = p;
        name.setText(playerModel.getName());
        score.setText(Integer.toString(playerModel.getTotalPoints()));
        heap.setText(Integer.toString(playerModel.getHeap().size()));
        fillCardPanel(cards,playerModel.getCards());
        repaint();
        revalidate();
    }
    
    public void setCard(Card c){
        taken_card = c;
        repaint();
        revalidate();
    }
    
    public ArrayList<Card> getSelectedCard(JPanel aPanel){
        CardView tv;
        ArrayList<Card> output = new ArrayList<>();
        
        for (Component c: aPanel.getComponents()){
            tv = (CardView)c;
            
            if (tv.isSelected())
                output.add(tv.getCard());
        }
        
        setCard(output.get(0));
        
        return output;
    }
    
    public void fillCardPanel (JPanel aPanel,ArrayList <Card> aList){
        aPanel.removeAll();
        
        for(Card t: aList){
            CardView aCardView = new CardView();
            aCardView.setCard(t);
            aCardView.setVisible(true);
            aPanel.add(aCardView);
        }
        
        aPanel.repaint();
        aPanel.revalidate();
    }
    
    /**
     * Creates new form PlayerView
     */
    public PlayerView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        cards = new javax.swing.JPanel();
        heap = new javax.swing.JLabel();

        name.setText("Nombre");

        score.setText("Score");

        cards.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cards.setLayout(new javax.swing.BoxLayout(cards, javax.swing.BoxLayout.LINE_AXIS));

        heap.setText("Heap");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cards, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(score, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(heap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(score)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(heap)
                .addGap(18, 18, 18)
                .addComponent(cards, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cards;
    private javax.swing.JLabel heap;
    private javax.swing.JLabel name;
    private javax.swing.JLabel score;
    // End of variables declaration//GEN-END:variables
}
