/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Games.Broom.GUI;

import GUI.CardView;
import GUI.Hand;
import GUI.SpanishCardBack;
import Games.Broom.Model.*;
import Model.*;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JPanel;
/**
 *
 * @author Javier
 */
public class PlayerView extends javax.swing.JPanel {
    private Player playerModel;
    private Broom escobaModel;
    private SpanishCard taken_card;

    public Player getPlayer() {
        return playerModel;
    }

    public JPanel getCards() {
        return cards;
    }    

    public SpanishCard getTakenCard() {
        return taken_card;
    }
    
    public void setBroom(Broom escobaModel){
        this.escobaModel = escobaModel;
        repaint();
        revalidate();
    }
    public void setPlayer(Player p){
        playerModel = p;
        name.setText(playerModel.getName());
        score.setText(Integer.toString(playerModel.getTotalPoints()));
        this.cards.addSelectionAtMouseListening();
        this.cards.add((ArrayList<Card>)(ArrayList<? extends Card>)playerModel.getCards(), SpanishCardBack.RED, false);
        repaint();
        revalidate();
    }
    
    public void setCard(SpanishCard c){
        taken_card = c;
        repaint();
        revalidate();
    }
    
    public ArrayList<SpanishCard> getSelectedCard(JPanel aPanel){
        CardView tv;
        ArrayList<SpanishCard> output = new ArrayList<>();
        
        for (Component c: aPanel.getComponents()){
            tv = (CardView)c;
            
            if (tv.isSelected())
                output.add((SpanishCard)tv.getCard());
        }
        
        setCard(output.get(0));
        
        return output;
    }
       
    /**
     * Creates new form PlayerView
     */
    public PlayerView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        cards = new GUI.Hand();

        name.setText("Nombre");

        score.setText("Score");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cards, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(score, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(score)
                .addGap(18, 18, 18)
                .addComponent(cards, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.Hand cards;
    private javax.swing.JLabel name;
    private javax.swing.JLabel score;
    // End of variables declaration//GEN-END:variables
}
